#!/usr/bin/env bash

# go to script dir
cd "$(dirname "$(readlink -f "$0")")"

# create data dir
if ! [[ -d "$(pwd)/data" ]]; then
    mkdir "$(pwd)/data"
fi
# remove old data
if [[ $1 == '-f' ]]; then
    rm -f "$(pwd)/data"/*
fi

# print header
cat headers/* 2>/dev/null

# get widgets results
col=$(grep 'col=' ./config | sed 's/.*col=//')
cd widgets
# execute widgets in columns
for i in $(seq 1 "${col}"); do
    for w in $(awk '!/^#/ {print $'$i'}' ../config); do
        # append content
        [ -e "${w}" ] && f[$i]="${f[$i]} $(./${w})\n"
    done
done

# print
motd=''
for c in "${f[@]}"; do
    [[ -z ${motd} ]] && motd="${c}" || motd=$(paste <(echo -e "${motd}") <(echo -e "${c}") -d'@')
done
echo -e "${motd}" | column -ts '@'

# print messages
cd ..
cat messages/* 2>/dev/null

exit 0
