#!/usr/bin/env bash

# system info:                            network:
#   system load:   0.00  process:  99       public ip:   10.20.30.40
#   cpu usage:     0%    uptime:   10d      private ip:  192.168.1.2
#   memory usage:  10%   users:    1
#                                         certificates:
# services:                                 google.fr        valid  01/01/2020
#   apparmor:    active    cron:  active    debian.org       valid  01/01/2020
#   logrotate:   inactive  lxc:   active    wikipedia.org    valid  01/01/2020
#   networking:  active    sshd:  active
#                                         disk usage:
# lxc status:                                        Size  Used  Free  Use%
#   git:   stopped  mailer:  stopped        /       10.0G  1.0G  9.0G   10%
#   dlna:  running  plex:    stopped

# go to script dir
cd "$(dirname "$(readlink -f "$0")")"

# remove old values
if [[ $1 == '-f' ]]; then
    rm -f /tmp/.motd.*
fi

# print header
cat headers/*

# get widgets results
cd widgets
col=$(grep 'col=' ../config | sed 's/.*col=//')
# execute widgets in columns
for i in $(seq 1 "${col}"); do
    for w in $(awk '!/^#/ {print $'$i'}' ../config); do
        # append content
        [ -e "${w}" ] && f[$i]="${f[$i]} $(./${w})\n"
    done
done

# print
motd=''
for c in "${f[@]}"; do
    [[ -z ${motd} ]] && motd="${c}" || motd=$(paste <(echo -e "${motd}") <(echo -e "${c}") -d'@')
done
echo -e "${motd}"| sed 's,@, @ ,' | column -ts '@'

