#!/usr/bin/env bash

# go to script dir
cd "$(dirname "$(readlink -f "$0")")"

# create data dir
if ! [[ -d "$(pwd)/data" ]]; then
  mkdir "$(pwd)/data"
fi
# remove old data
if [[ $1 == '-f' ]]; then
  rm -f "$(pwd)/data"/*
fi

# print header
cat headers/*

# Gather user's config
if ! [[ -f "$(pwd)/config" ]]; then
  echo "Please create a config file following the config-example file."
  exit 2
else
  . ./config
fi

# get widgets results
cd widgets

# execute widgets in columns
for i in $(seq 1 "${col}"); do
  for w in $(awk '// {print $'$i'}' <<<${layout[@]}); do
    # append content
    [ -e "${w}" ] && f[$i]="${f[$i]} $(./${w})\n"
  done
done

# print
motd=''
for c in "${f[@]}"; do
  [[ -z ${motd} ]] && motd="${c}" || motd=$(paste <(echo -e "${motd}") <(echo -e "${c}") -d'@')
done
echo -e "${motd}"| sed 's,@, @ ,' | column -ts '@'
