#!/usr/bin/env bash

# version permission
if [ "$(id -u)" != "0" ]; then
    echo >&2 "error: permission denied"
    echo >&2 'installation requires root privileges'
    exit 1
fi

# go to script dir
cd "$(dirname "$(readlink -f "$0")")"

# parse args
while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
    case "$1" in
        -u|--user)      shift; user="$1";;
    esac
    shift
done

if [[ -z "${user}" ]]; then
    echo >&2 "usage: ./$(basename "${0}") --user <USER>"
    exit 1
fi

# get homedir
home="$(getent passwd "${user}" | cut -d: -f6)"

# motd file
motd='/tmp/.motd/out'

# add cron rule
cron='/etc/cron.hourly/tinymotd'
echo "[+] add cron in ${cron}"
cat <<EOF > "${cron}"
#!/usr/bin/env bash
$(pwd)/generate > "${motd}"
EOF
chmod +x "${cron}"

# add print 
bashrc="${home}/.bashrc"
echo "[+] add motd load in ${bashrc}"
cat <<EOF >> "${bashrc}"
# motd supervision
if [[ -f "${motd}" ]]; then
    cat "${motd}"
fi
EOF
