#!/usr/bin/env bash

# partitions usage:
#              Size  Used  Free  Use%
#   /         10.0G  1.0G  9.0G   10%

disk_warn=80 # %
filter='nothing' # excluded target separated by |

#width=10
#bar() {
#    ((elapsed=$1*$2/100))
#    printf -v prog  "%${elapsed}s"
#    printf -v total "%$(($2-elapsed))s"
#    #printf '%s\n' "[${prog// /o}${total}]"
#    printf '%s\n' "[${prog// /o}${total}]"
#}

source ../tools/colors.sh
mapfile -t dfs < <(df -hT | grep -vE "tmpfs|vfat|${filter}" | tail -n+2 | sort -k7)
out=" |Size|Used|Free|Use%\n"
for line in "${dfs[@]}"; do
    IFS=" " read device type size used avail pcent target <<< "${line}"
    pcentnb=$(echo ${pcent} | sed 's,%,,')
    pcent=$(c_if "${pcentnb}" '<' "${disk_warn}" '%')
    #out+="${target}|$(bar $pcentnb $width)|$pcent|of ${size}\n"
    out+="${target}|${size}|${used}|${avail}|${pcent}\n"
done

echo
echo 'partitions usage:'
echo -e "${out}" | column -ts'|' | sed 's,^,  ,'
