#!/usr/bin/env bash

# packages:
#   4 upgradable  2 security
#   3 cleanable   0 obsolete
#   ! reboot required

date=$(date +%Y%m%d)
data='../data/apt'
columns=2

source ../tools/colors.sh
[[ -r "${data}" ]] && source "${data}"

# Comment a line to disable
packages_query=(
  "?upgradable                                 upgradable"
  "?and(?upgradable,?origin(Debian-Security))  security"
  "?or(?garbage,?config-files)                 cleanable"
  "?obsolete                                   obsolete"
#  "?garbage                                    removable"
#  "?config-files                               residual"
)

if [[ "${lastupdate}" != "${date}" ]]; then
    apt-get -qq update
    {
      echo "lastupdate=${date}"
      for entry in "${packages_query[@]}"; do
          IFS=" " read -r query label <<< "${entry}"
          value=$(apt -qq list "${query}" 2>/dev/null | wc -l)
          echo "${label,,}_pkgs=${value}"
      done
    } > "${data}"
    # read to source to load values
    source "${data}"
fi

out=''
for i in "${!packages_query[@]}"; do
    IFS=" " read -r _ label <<< "${packages_query[$i]}"
    var="${label,,}_pkgs"
    value=$(c_if "${!var}" '<' '1')
    out+="${value} ${label}|"
    (( (i+1) % columns == 0 )) && out+=$'\n'
done
if [[ -z "${out}" ]]; then
    out='none'
fi
out+='\n'

echo
echo 'packages:'
echo -e "${out}" | column -ts '|' | sed -e 's/^/  /'

if [[ -f /run/reboot-required ]]; then
    echo -e "  ${bred}!${reset} reboot required"
fi

