#!/usr/bin/env bash

# docker containers:
#  alpine  exited  nginx  up
#  blog    exited  git    up

source ../config

mapfile -t containers < <(docker ps -a --format "{{.Names}} {{.Status}}" | awk '!/^('${docker_filter}')/{print $1,$2}')

out=''
source ../tools/colors.sh
for i in "${!containers[@]}"; do
    IFS=" " read name status <<< "${containers[$i]}"
    status=$(c_match "${status}" 'Up')
    out+="${name}|${status,,}|"
    (( $(( (i+1) % docker_columns )) == 0 )) && out+='\n'
done
if [[ -z "${out}" ]]; then
    out='none'
fi
out+='\n'

echo
echo 'docker containers:'
echo -e "${out}" | column -ts '|' | sed -e 's/^/  /'
