#!/usr/bin/env bash
# /!\ Need docker binary

# containers:
#  o alpine  x nginx
#  o blog    x git

columns=2
filter='nothing'  # excluded containers separated by |

mapfile -t containers < <(docker ps -a --format "{{.Names}} {{.State}}" | awk '!/^('${filter}')/{print $1,$2}')

out=''
source ../tools/colors.sh
for i in "${!containers[@]}"; do
    IFS=" " read name state <<< "${containers[$i]}"
    state=$(c_match_r "${state}" 'running' 'o' 'x')
    out+="${state}|${name}|"
    (( $(( (i+1) % columns )) == 0 )) && out+='\n'
done
if [[ -z "${out}" ]]; then
    out='none'
fi
out+='\n'

echo
echo 'containers:'
echo -e "${out}" | column -ts '|' | sed -e 's/^/  /'
