#!/usr/bin/env bash

#  lxc status:
#    git   stopped  mailer  stopped
#    dlna  running  plex    stopped

source ../config

mapfile -t containers < <(lxc-ls -f | awk '!/^('${lxc_filter}')/{print $1,$2}' | sed '/^\s*$/d' | tail -n+2)

out=''
source ../tools/colors.sh
for i in "${!containers[@]}"; do
    IFS=" " read name status <<< "${containers[$i]}"
    status=$(c_match "${status}" 'RUNNING')
    out+="${name}|${status,,}|"
    (( $(( (i+1) % lxc_columns )) == 0 )) && out+='\n'
done
if [[ -z "${out}" ]]; then
    out='none'
fi
out+='\n'

echo
echo 'containers:'
echo -e "${out}" | column -ts '|' | sed -e 's/^/  /'
