#!/usr/bin/env bash

# partitions usage:
#   30%  /      50%  /backup
#   25%  /data

columns=2
disk_warn=80 # %
filter='_nothing_' # excluded target separated by |

#width=7
#bar() {
#    ((elapsed=$1*$2/100))
#    printf -v prog  "%${elapsed}s"
#    printf -v total "%$(($2-elapsed))s"
#    #printf '%s\n' "[${prog// /o}${total}]"
#    printf '%s\n' "[${prog// /o}${total}]"
#}

source ../tools/colors.sh
mapfile -t dfs < <(df -hT | grep -vE "tmpfs|vfat|efivarfs|${filter}" | tail -n+2 | sort -k7)

for i in "${!dfs[@]}"; do
    IFS=" " read device type size used avail pcent target <<< "${dfs[${i}]}"
    pcentnb=$(echo ${pcent} | sed 's,%,,')
    pcent=$(c_if "${pcentnb}" '<' "${disk_warn}" '%')
    out+="${pcent}|${target}|"
    #out+="$(bar ${pcentnb} ${width})|${pcent}|${target}|"
    (( $(( (i+1) % columns )) == 0 )) && out+='\n'
done

echo
echo 'partitions usage:'
echo -e "${out}" | column -ts'|' | sed 's,^,  ,'
