#!/usr/bin/env bash

#  services:
#    x lxc  o firewall  o sshd

columns=3
units=(    'lxc' 'nftables' 'sshd')
svc_names=('lxc' 'firewall' 'ssh')

out=''
source ../tools/colors.sh
for i in "${!units[@]}"; do
    svc_status=$(systemctl is-active "${units[${i}]}")
    svc_status=$(c_match_r "${svc_status}" 'active' 'o' 'x')
    out+="${svc_status} ${svc_names[$i]}|"
    (( $(( (i+1) % columns )) == 0 )) && out+='\n'
done
out+='\n'

echo
echo 'services:'
echo -e "${out}" | column -ts '|' | sed -e 's/^/  /'
